nelmio_api_doc:
    documentation:
        info:
            title: Allo Zo√© APIDoc
            description: AlloZoe API doc
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
            - ^/auth
            - ^/restaurants
            - ^/menus
            - ^/clients
            - ^/users
            - ^/delivers
            - ^/orders
